# An example of ClusterConfig with a normal nodegroup and a Fargate profile.
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aiplatform
  region: ap-northeast-2
  version: "1.17"

nodeGroups:
  - name: ng
    desiredCapacity: 4
    minSize: 3
    maxSize: 6
    instanceType: m5.xlarge

