issuer: http://dex.auth.svc.cluster.local:5556/dex
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
logger:
  level: "debug"
  format: text
oauth2:
  skipApprovalScreen: true
enablePasswordDB: true
staticPasswords:
- email: admin@kubeflow.org
  #hash: JDJhJDEwJEVJaThsTUlUdWFpTnBFdElIRS5aVWVDWHNPR1VzZVZWZU5tZ1FmUWlVMEZCOUIzZDMvNk9P
  # change password to "6team1234!"
  hash: $2b$10$rmAuxvZ1u82/o5.wafUBfuA4G8UncVY5mAAA/xut7gxtKfgQV5fOa
  username: admin
  userID: 08a8684b-db88-4b73-90a9-3cd1661f5466
staticClients:
- id: kubeflow-oidc-authservice
  redirectURIs: ["/login/oidc"]
  name: 'Dex Login Application'
  secret: pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok
